FROM debian:stable-slim

RUN apt update


RUN apt install -qqy dbus-daemon


# hier weiter
# https://github.com/AkihiroSuda/containerized-systemd/blob/master/Dockerfile.ubuntu-20.04
# build
# cd ./src
# docker buildx build --progress=plain -t docker_debian_slim_lastest -f Dockerfile "."

# run
# docker run -ti docker_debian_slim_lastest bash