FROM debian:stable-slim

RUN apt update

RUN set -xe \
    && DEBIAN_FRONTEND=noninteractive \
    && apt update \
    && apt install -qq --yes --purge --no-install-recommends --no-install-suggests procps \
    dbus-daemon \
    systemd \
    systemd-sysv \
    dbus \
    dbus-user-session \
    sudo 
    # perl \
    # locales \
    # locales-all

# FROM HERE
# https://stackoverflow.com/questions/56757169/is-there-a-way-to-suppress-update-alternatives-warning-skip-creation-warning

# RUN  sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen  \
#     && dpkg-reconfigure locales  \
#     && localectl set-locale LANG=en_US.UTF-8 

# add user $USER
ENV PUID='1000' \
    PGID='1000' \
    USER='user' 

RUN groupadd --gid "$PGID" "$USER" && \
    useradd --home-dir /home/$USER --shell /bin/bash --uid "$PUID" --gid "$PGID" "$USER" && \
    mkdir /home/$USER && \
    chown -R $USER:$USER /home/$USER && \
    usermod -aG sudo "$USER" && \
    usermod -aG adm "$USER" && \
    cp /etc/skel/.bashrc /home/user/

# add $USER to sudoers
RUN mkdir -p /etc/sudoers.d && \
    echo "user ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/"${USER}"  && \
    chmod 0440 /etc/sudoers.d/"$USER" && \
    cp /etc/skel/.bashrc /home/${USER}


COPY dbus/docker-dbus-entrypoint.sh  opt/

# clean up
RUN apt-get autoremove --yes --auto-remove  && \
    apt-get clean -y && \
    apt-get autoclean -y && \
    rm -rf /var/lib/apt/lists/*


RUN chmod +x /opt/docker-dbus-entrypoint.sh
ENTRYPOINT ["/opt/docker-dbus-entrypoint.sh"] 

# hier weiter
# https://github.com/AkihiroSuda/containerized-systemd/blob/master/Dockerfile.ubuntu-20.04
# build
# cd ./src
# docker buildx build --progress=plain -t docker_debian_slim_dbus -f Dockerfile_debian_stable_slim_dbus "."

# run
# docker run -ti docker_debian_slim_dbus bash