FROM debian:stable-slim


RUN set -xe \
    && DEBIAN_FRONTEND=noninteractive \
    && apt update \
    && apt install -yqq --purge --no-install-recommends --no-install-suggests procps 
    # perl \
    # locales \
    # locales-all \
    # systemd 

# RUN cat /etc/locale.gen

# RUN  sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen  \
#    && dpkg-reconfigure locales  \
#    && localectl set-locale LANG=en_US.UTF-8 

# clean up
RUN apt-get autoremove --yes --auto-remove  && \
    apt-get clean -y && \
    apt-get autoclean -y && \
    rm -rf /var/lib/apt/lists/*  

# build
# cd ./src
# docker buildx build --progress=plain -t docker_debian_slim -f Dockerfile_debian_stable_slim "."

# run
# docker run -ti docker_debian_slim bash