FROM debian:stable-slim

RUN apt update

# build
# cd ./src
# docker buildx build --progress=plain -t docker_debian_slim_lastest -f Dockerfile "."

# run
# docker run -ti docker_debian_slim_lastest bash